title: Matt Jonkers # your name (or website title) here
logo: "/images/mattprofile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am embarking on a career transition into data analytics. 
  With a background in Regulatory Complaince I discovered a passion for data. I am eager to show my analytical mind and probelm solving skills.
  I am currently undertaking the Data Accelerator Bootcamp to build projects using Excel, Tableau and SQL.<br><br> 
  <a href="https://www.linkedin.com/in/matt-jonkers/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
