title: Matt Jonkers # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Data Analyst 
<br><br>
Hi there! I'm Matt, a passionate individual embarking on a career transition into the world of data analytics. 
With a background in Regulatory Compliance with investigations experience, I've now developed a passion for data. 
I'm eager to leverage my pervious experience and show my analytical mindset and problem-solving abilities to dive deeper into the realm of data.
<br><br>
I am currently completing a data accelator bootcamp to build projects using Excel, Tableau and SQL. 
<br><br>
  <a href="https://www.linkedin.com/in/matt-jonkers/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
