title: Matt Jonkers # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there, I'm Matt a passionate individual embarking on a career transition into data analytics. 
  I want some pizza  <br><br>
  <a href="https://www.linkedin.com/in/averyjsmith/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
